/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.FrmGestionMesa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author carlos
 */
public class FrmCategoriaAPMuestra extends javax.swing.JFrame {
     private List<JButton> botones;


    /**
     * Creates new form FrmCategoriaAPMuestra
     */
    public FrmCategoriaAPMuestra() {
        initComponents();
        botones = new ArrayList<>();
        botonesCategoria();
    }

    private void botonesCategoria() {
        // Lista para almacenar los nombres de las categorías
        List<String> nombresCategorias = new ArrayList<>();

        // Leer el archivo y extraer los nombres de las categorías
        try (BufferedReader br = new BufferedReader(new FileReader("Productos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                // Dividir la línea por el punto y coma (;)
                String[] partes = linea.split(";");
                if (partes.length == 4) {
                    String nombreCategoria = partes[0];

                    // Agregar el nombre de categoría si no está ya en la lista
                    if (!nombresCategorias.contains(nombreCategoria)) {
                        nombresCategorias.add(nombreCategoria);
                    }
                } else {
                    System.err.println("Formato incorrecto en línea: " + linea);
                }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
            return; // Detener ejecución si ocurre un error
        }

        // Ordenar la lista de nombres de categorías
        Collections.sort(nombresCategorias);

        // Crear los botones para las categorías
        for (String nombreCategoria : nombresCategorias) {
            // Crear el botón
            JButton btnCat = new JButton( nombreCategoria);
            panelCategorias.add(btnCat); // Agregar al panel
            botones.add(btnCat); // Agregar a la lista de botones

            // Acción del botón
            btnCat.addActionListener(e -> {
                System.out.println(nombreCategoria);

                // Abrir la ventana de gestión para esta categoría
                FrmGestionMesa gestionMesa = new FrmGestionMesa();
                gestionMesa.setVisible(true);
            });
        }

        // Actualizar el panel usando .updateUI()
        panelCategorias.updateUI();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        scrpCategorias = new javax.swing.JScrollPane();
        panelCategorias = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        lbTitulo.setText("Categorias");

        panelCategorias.setLayout(new java.awt.GridLayout());
        scrpCategorias.setViewportView(panelCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(scrpCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(scrpCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaAPMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaAPMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaAPMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaAPMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCategoriaAPMuestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JScrollPane scrpCategorias;
    // End of variables declaration//GEN-END:variables
}
